-- Safe migration — run this in Supabase Dashboard → SQL Editor.
-- Uses IF NOT EXISTS so it's safe to run multiple times on an existing project.
-- Drops old conflicting policies before recreating them.

-- ── Tables ────────────────────────────────────────────────────────────────────

create table if not exists public.experiences (
  id          bigint primary key generated by default as identity,
  title       text not null default '',
  company     text not null default '',
  period      text not null default '',
  description text not null default '',
  created_at  timestamptz default now()
);

create table if not exists public.projects (
  id          bigint primary key generated by default as identity,
  title       text not null default '',
  description text not null default '',
  tags        text[] default '{}',
  github      text default '',
  live        text default '',
  created_at  timestamptz default now()
);

create table if not exists public.photos (
  id         bigint primary key generated by default as identity,
  url        text not null default '',
  alt        text default '',
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id         bigint primary key generated by default as identity,
  name       text not null default '',
  email      text not null default '',
  message    text not null default '',
  created_at timestamptz default now()
);

-- ── RLS ───────────────────────────────────────────────────────────────────────

alter table public.experiences enable row level security;
alter table public.projects    enable row level security;
alter table public.photos      enable row level security;
alter table public.messages    enable row level security;

-- Drop old policies (safe to re-run — ignores if they don't exist)
drop policy if exists "Public read experiences"   on public.experiences;
drop policy if exists "Public read projects"       on public.projects;
drop policy if exists "Public read photos"         on public.photos;
drop policy if exists "Public insert messages"     on public.messages;
drop policy if exists "Public read messages"       on public.messages;
drop policy if exists "Allow public read"          on public.experiences;
drop policy if exists "Allow public read"          on public.projects;
drop policy if exists "Allow public read"          on public.photos;

-- Recreate policies
create policy "Public read experiences"
  on public.experiences for select using (true);

create policy "Public read projects"
  on public.projects for select using (true);

create policy "Public read photos"
  on public.photos for select using (true);

-- Anyone can submit contact form; only service role can read/delete
create policy "Public insert messages"
  on public.messages for insert with check (true);

-- ── Storage bucket for photos ─────────────────────────────────────────────────
-- Run this only if the "photos" bucket doesn't exist yet.
insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do update set public = true;

-- Allow anyone to read photos from storage
drop policy if exists "Public read photo files" on storage.objects;
create policy "Public read photo files"
  on storage.objects for select
  using (bucket_id = 'photos');

-- Allow service role (our API) to upload / delete photo files
drop policy if exists "Service role manage photo files" on storage.objects;
create policy "Service role manage photo files"
  on storage.objects for all
  using (bucket_id = 'photos')
  with check (bucket_id = 'photos');
