-- Run this in Supabase Dashboard → SQL Editor to create tables and RLS.
-- Replace with your preferred schema name if needed.

-- Experiences (admin-managed, public read)
create table if not exists public.experiences (
  id bigint primary key generated by default as identity,
  title text not null,
  company text not null,
  period text not null,
  description text not null,
  created_at timestamptz default now()
);

-- Projects (admin-managed, public read)
create table if not exists public.projects (
  id bigint primary key generated by default as identity,
  title text not null,
  description text not null,
  tags text[] default '{}',
  github text default '',
  live text default '',
  created_at timestamptz default now()
);

-- Photos (admin-managed, public read)
create table if not exists public.photos (
  id bigint primary key generated by default as identity,
  url text not null,
  alt text default '',
  created_at timestamptz default now()
);

-- Contact messages (public insert, admin read/delete)
create table if not exists public.messages (
  id bigint primary key generated by default as identity,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz default now()
);

-- Enable RLS on all tables
alter table public.experiences enable row level security;
alter table public.projects enable row level security;
alter table public.photos enable row level security;
alter table public.messages enable row level security;

-- Public read for experiences, projects, photos
create policy "Public read experiences"
  on public.experiences for select
  using (true);

create policy "Public read projects"
  on public.projects for select
  using (true);

create policy "Public read photos"
  on public.photos for select
  using (true);

-- Messages: anyone can insert (contact form), no public read/delete (admin via service role)
create policy "Public insert messages"
  on public.messages for insert
  with check (true);

-- Optional: allow public to read their own message (skip if you only want admin to see)
-- No policy for select/delete = only service role can do it
