import { useEffect } from "react";
import { useLanguage } from "../../contexts/LanguageContext";

export const IS_TESTERS_HOST =
  typeof window !== "undefined" &&
  window.location.hostname.split(".")[0] === "testers";

export const TESTERS_BASE = IS_TESTERS_HOST ? "" : "/testers";

export const tPath = (p) => `${TESTERS_BASE}${p}` || "/";

export const IS_MAC =
  typeof navigator !== "undefined" &&
  /Mac|iPhone|iPad|iPod/.test(navigator.platform || navigator.userAgent);

const dict = {
  en: {
    siteTitle: "Device Testers",
    tagline: "Check your device, network, keyboard, camera and audio — right in the browser.",
    privacy: "Everything runs locally in your browser. No audio, video or keystroke data ever leaves your device.",
    home: "Home",
    keyboard: "Keyboard Tester",
    webcam: "Webcam Tester",
    audio: "Speaker & Mic Tester",
    device: "Device Information",
    network: "Network Quality Test",
    contactDeveloper: "Contact Developer",
    keyboardDesc: "Press every key and see it light up. US and Canadian French layouts for Windows and Mac.",
    webcamDesc: "Check your camera feed, resolution and frame rate, and take a test snapshot.",
    audioDesc: "Play left/right channel tones, watch your mic level, and record a playback test.",
    deviceDesc: "View your system, browser, display, connection and available device information.",
    networkDesc: "Measure latency, jitter, packet loss, download speed and upload speed.",
    contactDeveloperDesc: "Report a problem, suggest a test or send a message directly to the developer.",
    open: "Open tester",
    backToSite: "remker1.dev",
    // keyboard
    kbLayout: "Layout",
    kbPlatform: "Platform",
    kbUs: "US",
    kbWin: "Windows",
    kbMac: "Mac",
    kbCaFr: "Canadian French",
    kbNumpad: "Numpad",
    kbReset: "Reset",
    kbTested: "keys tested",
    kbHint: "Click here, then press any key on your keyboard.",
    kbLastKey: "Last key",
    kbNoKey: "No key pressed yet",
    kbHistory: "History",
    kbFnNote: "Grayed-out keys (like Fn) are handled by hardware and can't be detected by the browser. Some system shortcuts (e.g. ⌘+Tab, Win+L) are captured by the OS before reaching the page.",
    kbKey: "key",
    kbCode: "code",
    kbKeyCode: "keyCode",
    kbLocation: "location",
    // webcam
    wcStart: "Start camera",
    wcStop: "Stop camera",
    wcDevice: "Camera",
    wcMirror: "Mirror",
    wcSnapshot: "Take snapshot",
    wcResolution: "Resolution",
    wcFps: "Frame rate",
    wcMeasuredFps: "Measured FPS",
    wcIdle: "Camera is off. Click “Start camera” and allow access when prompted.",
    wcDenied: "Camera access was denied. Allow camera access in your browser's site settings, then try again.",
    wcNotFound: "No camera was found on this device.",
    wcInUse: "The camera appears to be in use by another app. Close it and try again.",
    wcError: "Could not start the camera",
    // audio
    spTitle: "Speaker test",
    spDesc: "Play a tone through each channel. You should hear it only on the matching side.",
    spLeft: "Left channel",
    spRight: "Right channel",
    spBoth: "Both channels",
    spStopTone: "Stop tone",
    spFreq: "Tone frequency",
    spOutput: "Output device",
    spOutputUnsupported: "Your browser doesn't support choosing an output device (Chrome or Edge required); the default speakers will be used.",
    micTitle: "Microphone test",
    micDesc: "Start the mic and speak — the level meter and waveform should move.",
    micStart: "Start microphone",
    micStop: "Stop microphone",
    micDevice: "Microphone",
    micLevel: "Input level",
    micRecord: "Record 5s clip",
    micRecording: "Recording…",
    micPlayback: "Playback",
    micSampleRate: "Sample rate",
    micDenied: "Microphone access was denied. Allow mic access in your browser's site settings, then try again.",
    micError: "Could not start the microphone",
    micRecUnsupported: "Recording is not supported in this browser.",
    // trackpad
    mouse: "Trackpad Tester",
    mouseDesc: "Check primary and secondary clicks, double-click speed, two-finger scrolling, pinch and pointer tracking.",
    msButtons: "Click test",
    msButtonsHint: "Click anywhere in this card. Try a normal click and your configured secondary-click gesture.",
    msLeft: "Primary click",
    msMiddle: "Middle",
    msRight: "Secondary click",
    msBack: "Back (M4)",
    msForward: "Forward (M5)",
    msDbl: "Double-click",
    msDblHint: "Double-click in the box — the interval between the two clicks is shown.",
    msDblCount: "double-clicks",
    msWheel: "Two-finger scroll & pinch",
    msWheelHint: "Scroll vertically and horizontally with two fingers, then pinch in and out inside the box.",
    msMove: "Pointer tracking",
    msMoveHint: "Move one finger around the trackpad. The trail reveals skips and the rate shows pointer events per second.",
    msMaxRate: "max",
    tpPinchIn: "pinch in",
    tpPinchOut: "pinch out",
    tpDisclaimer: "Browsers expose trackpads as pointer and wheel events, so this page cannot identify the hardware or capture system-level three- and four-finger gestures.",
    // screen
    screen: "Screen Tester",
    screenDesc: "Find dead pixels and backlight bleed, check gradients, and measure your real refresh rate.",
    scResolution: "Screen resolution",
    scViewport: "Browser window",
    scDpr: "Pixel ratio",
    scColorDepth: "Color depth",
    scRefresh: "Refresh rate (measured)",
    scDeadPixel: "Dead pixel & uniformity test",
    scDeadPixelDesc: "Fill the screen with solid colors and look for pixels that stay dark or show the wrong color. Use the gradient to check for banding and black to check backlight bleed.",
    scExitHint: "Click a swatch to go full screen. Click to cycle colors, press Esc to exit.",
    scOverlayHint: "Click: next color · Esc: exit",
    // touch
    touch: "Touch Tester",
    touchDesc: "Visualize multi-touch points and see how many fingers your screen tracks.",
    tcActive: "Active",
    tcMax: "Max",
    tcNoTouch: "This device doesn't report a touchscreen — the area below only responds to finger or pen input.",
    tcHint: "Touch here with one or more fingers.",
    tcFullscreen: "Full screen",
    tcExit: "Exit",
    // keyboard extras
    kbSimul: "Held now",
    kbMaxSimul: "Most at once",
    kbChatter: "Chatter suspects (re-trigger <35 ms)",
    kbNone: "none",
    battery: "Battery Tester",
    batteryDesc: "View live charge status and calculate battery health from your system's capacity values.",
    btIntro: "See the battery information your browser exposes and calculate capacity-based health accurately.",
    btLevel: "Charge level",
    btStatus: "Power status",
    btCharging: "Charging",
    btDischarging: "On battery",
    btUntilFull: "Time until full",
    btRemaining: "Estimated remaining",
    btApi: "Live data",
    btAvailable: "Available",
    btUnavailable: "Not supported",
    btHour: "h",
    btMinute: "m",
    btUnsupportedTitle: "Live battery data is unavailable",
    btUnsupported: "This browser does not provide the Battery Status API. You can still calculate battery health below using capacity values from your operating system.",
    btHealthTitle: "Battery health",
    btHealthDesc: "Enter the current full-charge capacity and original design capacity using the same unit (usually mWh or mAh).",
    btFullCapacity: "Current full-charge capacity",
    btDesignCapacity: "Design capacity",
    btFormula: "Health = current full-charge capacity ÷ design capacity × 100%",
    btHealthGood: "Good",
    btHealthWorn: "Noticeably worn",
    btHealthService: "Service recommended",
    btCheckValues: "The result is unusually high. Check that both values use the same unit and are entered in the correct fields.",
    btFindValues: "Where can I find these values?",
    btDetected: "Detected system:",
    btStepsWindows: "Run the command in Terminal or CMD. It saves battery-report.html in Downloads; the Open battery report button starts there. Under “Installed batteries” read DESIGN CAPACITY, FULL CHARGE CAPACITY and CYCLE COUNT — on dual-battery laptops, BATTERY 1 and BATTERY 2 are listed side by side, matching the cards above.",
    btStepsMac: "Run the command in Terminal: “DesignCapacity” is the design capacity, “AppleRawMaxCapacity” the current full-charge capacity, and “CycleCount” the cycle count.",
    btStepsLinux: "Each battery has its own folder (BAT0, BAT1…): energy_full is the full-charge capacity, energy_full_design the design capacity, cycle_count the cycle count.",
    btDisclaimer: "Web pages cannot directly read design capacity, full-charge capacity or cycle count. This calculator only uses values you provide and does not upload them.",
    btBattery: "Battery",
    btAddBattery: "Add battery",
    btRemove: "Remove battery",
    btCycles: "Cycle count (optional)",
    btCyclesNote: "Typical laptop batteries are rated for roughly 1000 charge cycles (about 500 on older models).",
    btCopy: "Click to copy",
    btCopied: "Copied",
    btAutoTitle: "Auto-fill from system output",
    btAutoFile: "Open battery-report.html",
    btAutoHint: "Paste the command output below — or drop the Windows battery-report.html file anywhere in this box — and every battery's values are filled in automatically. Parsing happens entirely on your device.",
    btAutoPlaceholder: "Paste ioreg / powercfg / uevent output here…",
    btAutoOk: "Recognized {n} battery(ies) — values filled in below.",
    btAutoFail: "Couldn't recognize that output. Make sure it comes from one of the commands shown below.",
    btTerminalReadyWindows: "Command copied. Press Win+R, type wt, press Enter, then press Ctrl+V and Enter to run it.",
    btTerminalReportWindows: "Return here and click Open battery-report.html to view the generated report.",
    btTerminalReadyMac: "Command copied. Press Command+Space, open Terminal, then press Command+V and Return to run it.",
    btTerminalCopyMac: "When the result appears, press Command+A to select all and Command+C to copy it.",
    btBrowserPasteMac: "Return here, click the Auto-fill box, and press Command+V to paste.",
    btTerminalReadyLinux: "Command copied. Press Ctrl+Alt+T, then press Ctrl+Shift+V and Enter to run it.",
    btTerminalCopyLinux: "When the result appears, press Ctrl+Shift+A to select all and Ctrl+Shift+C to copy it. If Select All is unavailable, use the terminal's Edit menu.",
    btBrowserPasteLinux: "Return here, click the Auto-fill box, and press Ctrl+V to paste.",
    diIntro: "See the device details your browser can safely provide, collected in one easy-to-copy report.",
    diCopy: "Copy device report",
    diCopied: "Report copied",
    diPrivacy: "This information is read locally. Nothing is uploaded when you view or copy the report.",
    diSystem: "System",
    diDisplay: "Display & input",
    diConnectivity: "Connection",
    diBrowserData: "Browser & devices",
    diOs: "Operating system",
    diBrowser: "Browser",
    diArchitecture: "Architecture",
    diModel: "Device model",
    diCpu: "Logical processors",
    diThreads: "threads",
    diMemory: "Approx. memory",
    diResolution: "Screen resolution",
    diViewport: "Browser window",
    diPixelRatio: "Pixel ratio",
    diColorDepth: "Color depth",
    diOrientation: "Orientation",
    diTouch: "Touch support",
    diPoints: "touch points",
    diNoTouch: "No touch detected",
    diOnline: "Online",
    diConnection: "Connection type",
    diDownlink: "Browser estimate",
    diRtt: "Browser RTT estimate",
    diDataSaver: "Data saver",
    diLanguage: "Languages",
    diTimezone: "Time zone",
    diCookies: "Cookies",
    diStorage: "Storage usage / quota",
    diCameras: "Cameras detected",
    diMicrophones: "Microphones detected",
    diSpeakers: "Audio outputs detected",
    diYes: "Yes",
    diNo: "No",
    diEnabled: "Enabled",
    diDisabled: "Disabled",
    diUnavailable: "Not exposed by this browser",
    ntIntro: "Measure latency, stability, download speed and upload speed using your selected test server.",
    ntStart: "Start network test",
    ntAgain: "Test again",
    ntServer: "Server",
    ntServerCloudflare: "Cloudflare",
    ntServerMlab: "M-Lab NDT7",
    ntSpeedUnit: "Speed unit",
    ntConnectedServer: "Connected server",
    ntMlabConsent: "I understand that M-Lab will record my public IP address and test results in its public dataset, and I consent to start this test.",
    ntMlabPolicy: "M-Lab privacy policy",
    ntTestingPing: "Measuring latency…",
    ntTestingDownload: "Testing download…",
    ntTestingUpload: "Testing upload…",
    ntStay: "Keep this tab open until the test finishes.",
    ntUnavailable: "The test server could not be reached. Check your connection and try again.",
    ntPing: "Latency",
    ntJitter: "Jitter",
    ntLoss: "Packet loss",
    ntDownload: "Download",
    ntUpload: "Upload",
    ntPingHint: "Lower is better; under 50 ms feels responsive.",
    ntJitterHint: "Lower means a steadier connection.",
    ntLossHint: "Ideally 0%; loss can interrupt calls and games.",
    ntDownloadHint: "Receiving data from the test server.",
    ntUploadHint: "Sending data to the test server.",
    ntQuality: "Connection quality",
    ntQualityGood: "Good",
    ntQualityFair: "Fair",
    ntQualityPoor: "Poor",
    ntQualityGoodDesc: "Suitable for video calls, streaming and everyday work.",
    ntQualityFairDesc: "Fine for normal browsing, but real-time calls may occasionally be affected.",
    ntQualityPoorDesc: "The connection may cause buffering, slow transfers or unstable calls.",
    ntDisclaimer: "Results measure the route to the selected server. Server distance, Wi-Fi load and browser activity can affect them, so compare results using the same server.",
    ntCostNotice: "No test service fee is charged. Tests use internet data and may transfer hundreds of megabytes on fast connections.",
    ctIntro: "Found a problem or have an idea for another tester? Send a message directly to the developer.",
    ctName: "Name",
    ctEmail: "Email",
    ctMessage: "Message",
    ctNamePlaceholder: "Your name",
    ctEmailPlaceholder: "you@example.com",
    ctMessagePlaceholder: "Describe the problem or suggestion…",
    ctSend: "Send message",
    ctSending: "Sending…",
    ctSentTitle: "Message sent",
    ctSentDesc: "Thanks for reaching out. Your message was delivered to the developer.",
    ctSendAnother: "Send another message",
    ctError: "The message could not be sent. Please check your connection and try again.",
    ctPrivacy: "Your name, email and message are sent only to the developer and stored with other website messages.",
  },
  zh: {
    siteTitle: "设备测试工具",
    tagline: "在浏览器里直接检查设备信息、网络、键盘、摄像头和音频。",
    privacy: "所有测试均在浏览器本地运行，任何音频、视频或按键数据都不会离开你的设备。",
    home: "首页",
    keyboard: "键盘测试",
    webcam: "摄像头测试",
    audio: "扬声器 & 麦克风测试",
    device: "设备信息",
    network: "网络质量测试",
    contactDeveloper: "联系开发者",
    keyboardDesc: "按下每个按键即可看到高亮反馈，支持 Windows 和 Mac 的 US、加拿大法语布局。",
    webcamDesc: "查看摄像头画面、分辨率和帧率，还可以拍一张测试快照。",
    audioDesc: "播放左右声道测试音，实时查看麦克风音量，并录音回放测试。",
    deviceDesc: "集中查看系统、浏览器、屏幕、网络和可用设备信息。",
    networkDesc: "检测延迟、抖动、丢包率、下载速度和上传速度。",
    contactDeveloperDesc: "报告问题、建议新的测试项目，或直接给开发者留言。",
    open: "开始测试",
    backToSite: "remker1.dev",
    kbLayout: "布局",
    kbPlatform: "平台",
    kbUs: "US",
    kbWin: "Windows",
    kbMac: "Mac",
    kbCaFr: "加拿大法语",
    kbNumpad: "数字小键盘",
    kbReset: "重置",
    kbTested: "个按键已测试",
    kbHint: "点击此区域，然后按下键盘上的任意键。",
    kbLastKey: "最近按键",
    kbNoKey: "还没有按下任何键",
    kbHistory: "按键记录",
    kbFnNote: "灰色按键（如 Fn）由硬件处理，浏览器无法检测。部分系统快捷键（如 ⌘+Tab、Win+L）会被操作系统拦截，页面收不到。",
    kbKey: "键值",
    kbCode: "键码",
    kbKeyCode: "keyCode",
    kbLocation: "位置",
    wcStart: "开启摄像头",
    wcStop: "关闭摄像头",
    wcDevice: "摄像头",
    wcMirror: "镜像",
    wcSnapshot: "拍摄快照",
    wcResolution: "分辨率",
    wcFps: "标称帧率",
    wcMeasuredFps: "实测帧率",
    wcIdle: "摄像头未开启。点击“开启摄像头”，并在弹窗中允许访问。",
    wcDenied: "摄像头权限被拒绝。请在浏览器的网站设置中允许摄像头访问后重试。",
    wcNotFound: "未检测到摄像头设备。",
    wcInUse: "摄像头可能被其他应用占用，请关闭后重试。",
    wcError: "无法启动摄像头",
    spTitle: "扬声器测试",
    spDesc: "分别播放左右声道测试音，你应该只在对应一侧听到声音。",
    spLeft: "左声道",
    spRight: "右声道",
    spBoth: "双声道",
    spStopTone: "停止播放",
    spFreq: "测试音频率",
    spOutput: "输出设备",
    spOutputUnsupported: "当前浏览器不支持选择输出设备（需 Chrome 或 Edge），将使用系统默认扬声器。",
    micTitle: "麦克风测试",
    micDesc: "开启麦克风后说话，音量条和波形应随声音变化。",
    micStart: "开启麦克风",
    micStop: "关闭麦克风",
    micDevice: "麦克风",
    micLevel: "输入音量",
    micRecord: "录制 5 秒",
    micRecording: "录音中…",
    micPlayback: "回放",
    micSampleRate: "采样率",
    micDenied: "麦克风权限被拒绝。请在浏览器的网站设置中允许麦克风访问后重试。",
    micError: "无法启动麦克风",
    micRecUnsupported: "当前浏览器不支持录音功能。",
    mouse: "触控板测试",
    mouseDesc: "测试主/辅助点按、双击速度、双指滚动、捏合手势和指针跟踪。",
    msButtons: "点按测试",
    msButtonsHint: "在此卡片内点按，分别尝试普通点按和你设置的辅助点按手势。",
    msLeft: "主点按",
    msMiddle: "中键",
    msRight: "辅助点按",
    msBack: "后退键 (M4)",
    msForward: "前进键 (M5)",
    msDbl: "双击测试",
    msDblHint: "在虚线框内双击，会显示两次点击的间隔。",
    msDblCount: "次双击",
    msWheel: "双指滚动 & 捏合",
    msWheelHint: "在框内双指上下、左右滚动，然后尝试向内和向外捏合。",
    msMove: "指针跟踪",
    msMoveHint: "用一根手指移动指针，轨迹可检查跳点，右上角显示每秒指针事件数。",
    msMaxRate: "最高",
    tpPinchIn: "向内捏合",
    tpPinchOut: "向外捏合",
    tpDisclaimer: "浏览器会把触控板表示为指针和滚轮事件，因此本页无法识别具体硬件，也无法捕获系统级三指、四指手势。",
    screen: "屏幕测试",
    screenDesc: "查找坏点和漏光、检查色阶渐变，并实测屏幕刷新率。",
    scResolution: "屏幕分辨率",
    scViewport: "浏览器窗口",
    scDpr: "像素比",
    scColorDepth: "色深",
    scRefresh: "刷新率（实测）",
    scDeadPixel: "坏点 & 均匀性测试",
    scDeadPixelDesc: "全屏填充纯色，寻找始终不变色的像素点；用渐变检查色阶断层，用黑色检查漏光。",
    scExitHint: "点击色块进入全屏；单击切换颜色，按 Esc 退出。",
    scOverlayHint: "单击：下一个颜色 · Esc：退出",
    touch: "触摸屏测试",
    touchDesc: "多点触控可视化，查看屏幕最多能同时识别几根手指。",
    tcActive: "当前触点",
    tcMax: "最多",
    tcNoTouch: "未检测到触摸屏——下方区域仅响应手指或触控笔输入。",
    tcHint: "用一根或多根手指触摸此区域。",
    tcFullscreen: "全屏测试",
    tcExit: "退出",
    kbSimul: "当前同时按下",
    kbMaxSimul: "最多同时",
    kbChatter: "连击可疑键（<35ms 重复触发）",
    kbNone: "无",
    battery: "电池测试",
    batteryDesc: "查看实时充电状态，并根据系统容量数据计算电池健康度。",
    btIntro: "查看浏览器能够读取的电池信息，并准确计算基于容量的健康度。",
    btLevel: "当前电量",
    btStatus: "供电状态",
    btCharging: "正在充电",
    btDischarging: "使用电池",
    btUntilFull: "预计充满",
    btRemaining: "预计剩余",
    btApi: "实时数据",
    btAvailable: "可读取",
    btUnavailable: "不支持",
    btHour: "小时",
    btMinute: "分钟",
    btUnsupportedTitle: "无法读取实时电池数据",
    btUnsupported: "当前浏览器不提供电池状态接口。你仍可在下方输入操作系统提供的容量数据来计算健康度。",
    btHealthTitle: "电池健康度",
    btHealthDesc: "输入当前满充容量和原始设计容量，两者须使用相同单位（通常为 mWh 或 mAh）。",
    btFullCapacity: "当前满充容量",
    btDesignCapacity: "设计容量",
    btFormula: "健康度 = 当前满充容量 ÷ 设计容量 × 100%",
    btHealthGood: "状态良好",
    btHealthWorn: "已有明显损耗",
    btHealthService: "建议检修或更换",
    btCheckValues: "结果异常偏高，请确认两个数值单位相同，并且没有填反。",
    btFindValues: "怎样查找这两个容量？",
    btDetected: "检测到当前系统：",
    btStepsWindows: "在终端或 CMD 中运行命令，battery-report.html 会保存到下载目录；点击“打开 battery-report.html”会默认从这里开始。在 Installed batteries 部分查看 DESIGN CAPACITY（设计容量）、FULL CHARGE CAPACITY（满充容量）和 CYCLE COUNT（循环次数）——双电池机型会并排列出 BATTERY 1 和 BATTERY 2，正好对应上方的电池卡片。",
    btStepsMac: "在终端运行命令：DesignCapacity 为设计容量，AppleRawMaxCapacity 为当前满充容量，CycleCount 为循环次数。",
    btStepsLinux: "每块电池一个目录（BAT0、BAT1…）：energy_full 为满充容量，energy_full_design 为设计容量，cycle_count 为循环次数。",
    btDisclaimer: "网页无法直接读取设计容量、满充容量或循环次数。本工具只使用你输入的数据，并且不会上传。",
    btBattery: "电池",
    btAddBattery: "添加电池",
    btRemove: "删除此电池",
    btCycles: "循环次数（选填）",
    btCyclesNote: "笔记本电池的设计循环寿命通常约为 1000 次（较旧机型约 500 次）。",
    btCopy: "点击复制",
    btCopied: "已复制",
    btAutoTitle: "从系统输出自动填充",
    btAutoFile: "打开 battery-report.html",
    btAutoHint: "把命令输出粘贴到下方——或把 Windows 生成的 battery-report.html 文件直接拖进此区域——所有电池的数值会自动识别填充。解析完全在你的设备上进行。",
    btAutoPlaceholder: "在此粘贴 ioreg / powercfg / uevent 的输出…",
    btAutoOk: "已识别 {n} 块电池，数值已自动填充。",
    btAutoFail: "无法识别该输出，请确认它来自下方给出的命令。",
    btTerminalReadyWindows: "命令已复制。按 Win+R，输入 wt 并回车，再按 Ctrl+V 粘贴并回车执行。",
    btTerminalReportWindows: "完成后回到本页，点击 Open battery-report.html 查看生成的报告。",
    btTerminalReadyMac: "命令已复制。按 Command+空格打开 Terminal，再按 Command+V 粘贴并回车执行。",
    btTerminalCopyMac: "结果出现后，按 Command+A 全选，再按 Command+C 复制。",
    btBrowserPasteMac: "回到本页，点击 Auto-fill 输入框，按 Command+V 粘贴。",
    btTerminalReadyLinux: "命令已复制。按 Ctrl+Alt+T 打开终端，再按 Ctrl+Shift+V 粘贴并回车执行。",
    btTerminalCopyLinux: "结果出现后，按 Ctrl+Shift+A 全选，再按 Ctrl+Shift+C 复制；如果全选快捷键不可用，请使用终端的编辑菜单。",
    btBrowserPasteLinux: "回到本页，点击 Auto-fill 输入框，按 Ctrl+V 粘贴。",
    diIntro: "集中查看浏览器能够安全读取的设备信息，并可一键复制为报告。",
    diCopy: "复制设备报告",
    diCopied: "报告已复制",
    diPrivacy: "查看和复制报告时，所有信息都只在本地读取，不会上传。",
    diSystem: "系统",
    diDisplay: "屏幕与输入",
    diConnectivity: "网络连接",
    diBrowserData: "浏览器与设备",
    diOs: "操作系统",
    diBrowser: "浏览器",
    diArchitecture: "处理器架构",
    diModel: "设备型号",
    diCpu: "逻辑处理器",
    diThreads: "线程",
    diMemory: "估算内存",
    diResolution: "屏幕分辨率",
    diViewport: "浏览器窗口",
    diPixelRatio: "像素比",
    diColorDepth: "色深",
    diOrientation: "屏幕方向",
    diTouch: "触控支持",
    diPoints: "个触控点",
    diNoTouch: "未检测到触控",
    diOnline: "已联网",
    diConnection: "连接类型",
    diDownlink: "浏览器估算带宽",
    diRtt: "浏览器估算 RTT",
    diDataSaver: "省流量模式",
    diLanguage: "语言",
    diTimezone: "时区",
    diCookies: "Cookie",
    diStorage: "已用 / 可用存储空间",
    diCameras: "检测到的摄像头",
    diMicrophones: "检测到的麦克风",
    diSpeakers: "检测到的音频输出",
    diYes: "是",
    diNo: "否",
    diEnabled: "已启用",
    diDisabled: "已禁用",
    diUnavailable: "当前浏览器未提供",
    ntIntro: "使用你选择的测试服务器检测延迟、稳定性、下载速度和上传速度。",
    ntStart: "开始网络测试",
    ntAgain: "重新测试",
    ntServer: "服务器",
    ntServerCloudflare: "Cloudflare",
    ntServerMlab: "M-Lab NDT7",
    ntSpeedUnit: "速度单位",
    ntConnectedServer: "连接的服务器",
    ntMlabConsent: "我了解 M-Lab 会把我的公网 IP 地址和测速结果记录到公开数据集中，并同意开始本次测试。",
    ntMlabPolicy: "M-Lab 隐私政策",
    ntTestingPing: "正在检测延迟…",
    ntTestingDownload: "正在检测下载速度…",
    ntTestingUpload: "正在检测上传速度…",
    ntStay: "测试完成前请保持此页面开启。",
    ntUnavailable: "无法连接测试服务器，请检查网络后重试。",
    ntPing: "延迟",
    ntJitter: "抖动",
    ntLoss: "丢包率",
    ntDownload: "下载速度",
    ntUpload: "上传速度",
    ntPingHint: "越低越好，低于 50 ms 通常响应流畅。",
    ntJitterHint: "越低代表连接越稳定。",
    ntLossHint: "理想值为 0%，丢包会影响通话和游戏。",
    ntDownloadHint: "从本站测试服务器接收数据的速度。",
    ntUploadHint: "向本站测试服务器发送数据的速度。",
    ntQuality: "连接质量",
    ntQualityGood: "良好",
    ntQualityFair: "一般",
    ntQualityPoor: "较差",
    ntQualityGoodDesc: "适合视频通话、高清视频和日常工作。",
    ntQualityFairDesc: "日常浏览没有问题，但实时通话偶尔可能受到影响。",
    ntQualityPoorDesc: "可能出现缓冲、传输缓慢或通话不稳定。",
    ntDisclaimer: "结果反映的是到所选服务器的线路质量。服务器距离、Wi-Fi 负载和浏览器活动都会影响结果，比较结果时请使用同一服务器。",
    ntCostNotice: "测速服务不会产生费用，但会使用网络流量；高速连接一次测试可能传输数百 MB 数据。",
    ctIntro: "发现问题或希望增加新的测试工具？可以直接给开发者发送消息。",
    ctName: "姓名",
    ctEmail: "邮箱",
    ctMessage: "留言内容",
    ctNamePlaceholder: "你的名字",
    ctEmailPlaceholder: "you@example.com",
    ctMessagePlaceholder: "请描述问题或建议…",
    ctSend: "发送消息",
    ctSending: "正在发送…",
    ctSentTitle: "消息已发送",
    ctSentDesc: "感谢你的留言，消息已经发送给开发者。",
    ctSendAnother: "再发一条消息",
    ctError: "消息发送失败，请检查网络后重试。",
    ctPrivacy: "你的姓名、邮箱和留言只会发送给开发者，并与网站留言一起保存。",
  },
  fr: {
    siteTitle: "Testeurs d'appareils",
    tagline: "Vérifiez votre appareil, votre réseau, votre clavier, votre caméra et votre audio dans le navigateur.",
    privacy: "Tout s'exécute localement dans votre navigateur. Aucune donnée audio, vidéo ou de frappe ne quitte votre appareil.",
    home: "Accueil",
    keyboard: "Test du clavier",
    webcam: "Test de la webcam",
    audio: "Test haut-parleurs & micro",
    device: "Informations de l'appareil",
    network: "Test de qualité réseau",
    contactDeveloper: "Contacter le développeur",
    keyboardDesc: "Appuyez sur chaque touche pour la voir s'illuminer. Dispositions US et français canadien pour Windows et Mac.",
    webcamDesc: "Vérifiez l'image de votre caméra, la résolution et la fréquence d'images, et prenez une capture d'essai.",
    audioDesc: "Jouez des tonalités gauche/droite, surveillez le niveau du micro et testez un enregistrement.",
    deviceDesc: "Consultez les informations du système, du navigateur, de l'écran, du réseau et des périphériques.",
    networkDesc: "Mesurez la latence, la gigue, la perte de paquets et les débits descendant et montant.",
    contactDeveloperDesc: "Signalez un problème, proposez un test ou envoyez un message au développeur.",
    open: "Ouvrir le testeur",
    backToSite: "remker1.dev",
    // keyboard
    kbLayout: "Disposition",
    kbPlatform: "Plateforme",
    kbUs: "US",
    kbWin: "Windows",
    kbMac: "Mac",
    kbCaFr: "Français canadien",
    kbNumpad: "Pavé numérique",
    kbReset: "Réinitialiser",
    kbTested: "touches testées",
    kbHint: "Cliquez ici, puis appuyez sur n'importe quelle touche de votre clavier.",
    kbLastKey: "Dernière touche",
    kbNoKey: "Aucune touche pressée pour l'instant",
    kbHistory: "Historique",
    kbFnNote: "Les touches grisées (comme Fn) sont gérées par le matériel et ne peuvent pas être détectées par le navigateur. Certains raccourcis système (ex. ⌘+Tab, Win+L) sont interceptés par l'OS avant d'atteindre la page.",
    kbKey: "touche",
    kbCode: "code",
    kbKeyCode: "keyCode",
    kbLocation: "position",
    // webcam
    wcStart: "Démarrer la caméra",
    wcStop: "Arrêter la caméra",
    wcDevice: "Caméra",
    wcMirror: "Miroir",
    wcSnapshot: "Prendre une capture",
    wcResolution: "Résolution",
    wcFps: "Fréquence d'images",
    wcMeasuredFps: "FPS mesurés",
    wcIdle: "La caméra est éteinte. Cliquez sur « Démarrer la caméra » et autorisez l'accès.",
    wcDenied: "L'accès à la caméra a été refusé. Autorisez-le dans les paramètres du site de votre navigateur, puis réessayez.",
    wcNotFound: "Aucune caméra détectée sur cet appareil.",
    wcInUse: "La caméra semble utilisée par une autre application. Fermez-la et réessayez.",
    wcError: "Impossible de démarrer la caméra",
    // audio
    spTitle: "Test des haut-parleurs",
    spDesc: "Jouez une tonalité sur chaque canal. Vous ne devriez l'entendre que du côté correspondant.",
    spLeft: "Canal gauche",
    spRight: "Canal droit",
    spBoth: "Les deux canaux",
    spStopTone: "Arrêter la tonalité",
    spFreq: "Fréquence de la tonalité",
    spOutput: "Périphérique de sortie",
    spOutputUnsupported: "Votre navigateur ne permet pas de choisir le périphérique de sortie (Chrome ou Edge requis) ; les haut-parleurs par défaut seront utilisés.",
    micTitle: "Test du microphone",
    micDesc: "Démarrez le micro et parlez — le vumètre et la forme d'onde doivent réagir.",
    micStart: "Démarrer le micro",
    micStop: "Arrêter le micro",
    micDevice: "Microphone",
    micLevel: "Niveau d'entrée",
    micRecord: "Enregistrer 5 s",
    micRecording: "Enregistrement…",
    micPlayback: "Lecture",
    micSampleRate: "Fréquence d'échantillonnage",
    micDenied: "L'accès au micro a été refusé. Autorisez-le dans les paramètres du site de votre navigateur, puis réessayez.",
    micError: "Impossible de démarrer le micro",
    micRecUnsupported: "L'enregistrement n'est pas pris en charge par ce navigateur.",
    mouse: "Test du pavé tactile",
    mouseDesc: "Testez les clics principal et secondaire, le double-clic, le défilement à deux doigts, le pincement et le suivi.",
    msButtons: "Test des clics",
    msButtonsHint: "Cliquez dans cette carte avec un clic normal puis avec votre geste de clic secondaire configuré.",
    msLeft: "Clic principal",
    msMiddle: "Milieu",
    msRight: "Clic secondaire",
    msBack: "Retour (M4)",
    msForward: "Avant (M5)",
    msDbl: "Double-clic",
    msDblHint: "Double-cliquez dans la zone — l'intervalle entre les deux clics s'affiche.",
    msDblCount: "double-clics",
    msWheel: "Défilement à deux doigts & pincement",
    msWheelHint: "Faites défiler verticalement et horizontalement à deux doigts, puis pincez dans les deux sens.",
    msMove: "Suivi du pointeur",
    msMoveHint: "Déplacez un doigt sur le pavé tactile. Le tracé révèle les sauts et le taux indique les événements par seconde.",
    msMaxRate: "max",
    tpPinchIn: "pincer",
    tpPinchOut: "écarter",
    tpDisclaimer: "Le navigateur expose le pavé tactile comme des événements de pointeur et de molette ; il ne peut donc pas identifier le matériel ni capter les gestes système à trois ou quatre doigts.",
    screen: "Test de l'écran",
    screenDesc: "Repérez les pixels morts et les fuites de lumière, vérifiez les dégradés et mesurez la fréquence de rafraîchissement réelle.",
    scResolution: "Résolution de l'écran",
    scViewport: "Fenêtre du navigateur",
    scDpr: "Ratio de pixels",
    scColorDepth: "Profondeur de couleur",
    scRefresh: "Fréquence (mesurée)",
    scDeadPixel: "Pixels morts & uniformité",
    scDeadPixelDesc: "Remplissez l'écran de couleurs unies et cherchez les pixels qui restent sombres ou d'une mauvaise couleur. Utilisez le dégradé pour le banding et le noir pour les fuites de rétroéclairage.",
    scExitHint: "Cliquez sur une couleur pour passer en plein écran ; cliquez pour changer de couleur, Échap pour quitter.",
    scOverlayHint: "Clic : couleur suivante · Échap : quitter",
    touch: "Test tactile",
    touchDesc: "Visualisez les points de contact multi-touch et le nombre de doigts suivis.",
    tcActive: "Actifs",
    tcMax: "Max",
    tcNoTouch: "Cet appareil ne signale pas d'écran tactile — la zone ne réagit qu'au toucher (doigt ou stylet).",
    tcHint: "Touchez cette zone avec un ou plusieurs doigts.",
    tcFullscreen: "Plein écran",
    tcExit: "Quitter",
    kbSimul: "Enfoncées",
    kbMaxSimul: "Max simultané",
    kbChatter: "Touches suspectes (re-déclenchement <35 ms)",
    kbNone: "aucune",
    battery: "Test de la batterie",
    batteryDesc: "Affichez l'état de charge en direct et calculez la santé à partir des capacités système.",
    btIntro: "Consultez les données exposées par le navigateur et calculez précisément la santé basée sur la capacité.",
    btLevel: "Niveau de charge",
    btStatus: "État d'alimentation",
    btCharging: "En charge",
    btDischarging: "Sur batterie",
    btUntilFull: "Temps avant charge complète",
    btRemaining: "Autonomie estimée",
    btApi: "Données en direct",
    btAvailable: "Disponibles",
    btUnavailable: "Non pris en charge",
    btHour: "h",
    btMinute: "min",
    btUnsupportedTitle: "Données de batterie indisponibles",
    btUnsupported: "Ce navigateur ne fournit pas l'API Battery Status. Vous pouvez tout de même calculer la santé avec les capacités du système.",
    btHealthTitle: "Santé de la batterie",
    btHealthDesc: "Saisissez la capacité de charge complète actuelle et la capacité nominale avec la même unité (mWh ou mAh).",
    btFullCapacity: "Capacité de charge complète",
    btDesignCapacity: "Capacité nominale",
    btFormula: "Santé = capacité de charge complète ÷ capacité nominale × 100 %",
    btHealthGood: "Bon état",
    btHealthWorn: "Usure notable",
    btHealthService: "Entretien recommandé",
    btCheckValues: "Le résultat est anormalement élevé. Vérifiez les unités et l'ordre des valeurs.",
    btFindValues: "Où trouver ces valeurs ?",
    btDetected: "Système détecté :",
    btStepsWindows: "Exécutez la commande dans le Terminal ou CMD. Le fichier battery-report.html est enregistré dans Téléchargements et le bouton d'ouverture commence dans ce dossier. Sous « Installed batteries », lisez DESIGN CAPACITY, FULL CHARGE CAPACITY et CYCLE COUNT — sur les portables à deux batteries, BATTERY 1 et BATTERY 2 apparaissent côte à côte, comme les cartes ci-dessus.",
    btStepsMac: "Exécutez la commande dans le Terminal : « DesignCapacity » est la capacité d'origine, « AppleRawMaxCapacity » la capacité actuelle à pleine charge et « CycleCount » le nombre de cycles.",
    btStepsLinux: "Chaque batterie a son dossier (BAT0, BAT1…) : energy_full est la capacité à pleine charge, energy_full_design la capacité d'origine, cycle_count le nombre de cycles.",
    btDisclaimer: "Une page web ne peut pas lire directement les capacités ni le nombre de cycles. Ce calcul utilise seulement vos valeurs et ne les envoie pas.",
    btBattery: "Batterie",
    btAddBattery: "Ajouter une batterie",
    btRemove: "Retirer cette batterie",
    btCycles: "Nombre de cycles (optionnel)",
    btCyclesNote: "Les batteries de portables sont généralement conçues pour environ 1000 cycles (500 sur les modèles plus anciens).",
    btCopy: "Cliquer pour copier",
    btCopied: "Copié",
    btAutoTitle: "Remplissage automatique depuis la sortie système",
    btAutoFile: "Ouvrir battery-report.html",
    btAutoHint: "Collez la sortie de la commande ci-dessous — ou déposez le fichier battery-report.html de Windows dans cette zone — et les valeurs de chaque batterie sont remplies automatiquement. L'analyse se fait entièrement sur votre appareil.",
    btAutoPlaceholder: "Collez ici la sortie de ioreg / powercfg / uevent…",
    btAutoOk: "{n} batterie(s) reconnue(s) — valeurs remplies ci-dessous.",
    btAutoFail: "Sortie non reconnue. Vérifiez qu'elle provient de l'une des commandes ci-dessous.",
    btTerminalReadyWindows: "Commande copiée. Appuyez sur Win+R, saisissez wt, validez, puis utilisez Ctrl+V et Entrée pour l’exécuter.",
    btTerminalReportWindows: "Revenez ensuite ici et cliquez sur Open battery-report.html pour afficher le rapport généré.",
    btTerminalReadyMac: "Commande copiée. Appuyez sur Commande+Espace, ouvrez Terminal, puis utilisez Commande+V et Retour pour l’exécuter.",
    btTerminalCopyMac: "Lorsque le résultat apparaît, utilisez Commande+A pour tout sélectionner, puis Commande+C pour le copier.",
    btBrowserPasteMac: "Revenez ici, cliquez dans la zone de remplissage automatique, puis utilisez Commande+V pour coller.",
    btTerminalReadyLinux: "Commande copiée. Appuyez sur Ctrl+Alt+T, puis utilisez Ctrl+Maj+V et Entrée pour l’exécuter.",
    btTerminalCopyLinux: "Lorsque le résultat apparaît, utilisez Ctrl+Maj+A pour tout sélectionner, puis Ctrl+Maj+C pour le copier. Si la sélection totale n’est pas disponible, utilisez le menu Édition du terminal.",
    btBrowserPasteLinux: "Revenez ici, cliquez dans la zone de remplissage automatique, puis utilisez Ctrl+V pour coller.",
    diIntro: "Consultez les informations que le navigateur peut fournir en toute sécurité et copiez-les dans un rapport.",
    diCopy: "Copier le rapport",
    diCopied: "Rapport copié",
    diPrivacy: "Ces informations sont lues localement et ne sont pas envoyées lorsque vous consultez ou copiez le rapport.",
    diSystem: "Système",
    diDisplay: "Écran et saisie",
    diConnectivity: "Connexion",
    diBrowserData: "Navigateur et périphériques",
    diOs: "Système d'exploitation",
    diBrowser: "Navigateur",
    diArchitecture: "Architecture",
    diModel: "Modèle de l'appareil",
    diCpu: "Processeurs logiques",
    diThreads: "threads",
    diMemory: "Mémoire estimée",
    diResolution: "Résolution de l'écran",
    diViewport: "Fenêtre du navigateur",
    diPixelRatio: "Ratio de pixels",
    diColorDepth: "Profondeur de couleur",
    diOrientation: "Orientation",
    diTouch: "Prise en charge tactile",
    diPoints: "points tactiles",
    diNoTouch: "Aucun tactile détecté",
    diOnline: "En ligne",
    diConnection: "Type de connexion",
    diDownlink: "Débit estimé",
    diRtt: "RTT estimé",
    diDataSaver: "Économie de données",
    diLanguage: "Langues",
    diTimezone: "Fuseau horaire",
    diCookies: "Témoins",
    diStorage: "Stockage utilisé / quota",
    diCameras: "Caméras détectées",
    diMicrophones: "Microphones détectés",
    diSpeakers: "Sorties audio détectées",
    diYes: "Oui",
    diNo: "Non",
    diEnabled: "Activés",
    diDisabled: "Désactivés",
    diUnavailable: "Non fourni par ce navigateur",
    ntIntro: "Mesurez la latence, la stabilité et les débits avec le serveur de test sélectionné.",
    ntStart: "Démarrer le test réseau",
    ntAgain: "Tester à nouveau",
    ntServer: "Serveur",
    ntServerCloudflare: "Cloudflare",
    ntServerMlab: "M-Lab NDT7",
    ntSpeedUnit: "Unité de débit",
    ntConnectedServer: "Serveur connecté",
    ntMlabConsent: "Je comprends que M-Lab enregistrera mon adresse IP publique et les résultats dans son jeu de données public, et j'accepte de lancer ce test.",
    ntMlabPolicy: "Politique de confidentialité M-Lab",
    ntTestingPing: "Mesure de la latence…",
    ntTestingDownload: "Test du téléchargement…",
    ntTestingUpload: "Test de l'envoi…",
    ntStay: "Gardez cet onglet ouvert jusqu'à la fin du test.",
    ntUnavailable: "Le serveur de test est inaccessible. Vérifiez votre connexion et réessayez.",
    ntPing: "Latence",
    ntJitter: "Gigue",
    ntLoss: "Perte de paquets",
    ntDownload: "Téléchargement",
    ntUpload: "Envoi",
    ntPingHint: "Plus bas est mieux ; moins de 50 ms est réactif.",
    ntJitterHint: "Une valeur faible indique une connexion stable.",
    ntLossHint: "Idéalement 0 % ; les pertes perturbent appels et jeux.",
    ntDownloadHint: "Réception de données depuis le serveur de test.",
    ntUploadHint: "Envoi de données vers le serveur de test.",
    ntQuality: "Qualité de la connexion",
    ntQualityGood: "Bonne",
    ntQualityFair: "Moyenne",
    ntQualityPoor: "Faible",
    ntQualityGoodDesc: "Adaptée aux appels vidéo, à la diffusion et au travail quotidien.",
    ntQualityFairDesc: "Correcte pour la navigation, mais les appels en temps réel peuvent parfois être affectés.",
    ntQualityPoorDesc: "La connexion peut causer des ralentissements, de la mise en mémoire tampon ou des appels instables.",
    ntDisclaimer: "Les résultats mesurent le trajet vers le serveur sélectionné. La distance, le Wi-Fi et le navigateur peuvent les influencer ; comparez les résultats avec le même serveur.",
    ntCostNotice: "Aucun frais de service n'est facturé. Le test utilise des données Internet et peut transférer plusieurs centaines de Mo sur une connexion rapide.",
    ctIntro: "Vous avez trouvé un problème ou souhaitez proposer un nouveau test ? Envoyez un message au développeur.",
    ctName: "Nom",
    ctEmail: "Courriel",
    ctMessage: "Message",
    ctNamePlaceholder: "Votre nom",
    ctEmailPlaceholder: "vous@exemple.com",
    ctMessagePlaceholder: "Décrivez le problème ou votre suggestion…",
    ctSend: "Envoyer le message",
    ctSending: "Envoi…",
    ctSentTitle: "Message envoyé",
    ctSentDesc: "Merci. Votre message a été transmis au développeur.",
    ctSendAnother: "Envoyer un autre message",
    ctError: "Le message n'a pas pu être envoyé. Vérifiez votre connexion et réessayez.",
    ctPrivacy: "Votre nom, courriel et message sont envoyés uniquement au développeur et conservés avec les autres messages du site.",
  },
};

export function useT() {
  const { lang } = useLanguage();
  return (key) => dict[lang]?.[key] ?? dict.en[key] ?? key;
}

export function useDocTitle(suffix) {
  useEffect(() => {
    const prev = document.title;
    document.title = suffix ? `${suffix} · testers.remker1.dev` : "testers.remker1.dev";
    return () => {
      document.title = prev;
    };
  }, [suffix]);
}
